In [1]:
import numpy  as np
import math

In [2]:
# Anchors 中def create_anchors(scales,ratios,shape,feature_stride,anchor_stride)
scales = 32
ratios = [0.5, 1, 2]
shape = (256, 256)
feature_stride = 4
anchor_stride = 1

In [3]:
scales, ratios = np.meshgrid(np.array(scales),np.array(ratios))
print(scales)
print(ratios)

[[32]
 [32]
 [32]]
[[0.5]
 [1. ]
 [2. ]]


In [4]:
scales = scales.flatten()
ratios = ratios.flatten()
print(scales)
print(ratios)

[32 32 32]
[0.5 1.  2. ]


In [5]:
heights = scales / np.sqrt(ratios)
widths = scales * np.sqrt(ratios)
print(heights)
print(widths)

[45.254834 32.       22.627417]
[22.627417 32.       45.254834]


In [10]:
shifts_y = np.arange(0, shape[0], anchor_stride) * feature_stride
print(shifts_y)
shifts_x = np.arange(0, shape[1], anchor_stride) * feature_stride
print(shifts_x)
shifts_x, shifts_y = np.meshgrid(shifts_x, shifts_y)
print(shifts_x)
print("len:",len(shifts_x))
print(shifts_y)
print("len:",len(shifts_y))

[   0    4    8   12   16   20   24   28   32   36   40   44   48   52
   56   60   64   68   72   76   80   84   88   92   96  100  104  108
  112  116  120  124  128  132  136  140  144  148  152  156  160  164
  168  172  176  180  184  188  192  196  200  204  208  212  216  220
  224  228  232  236  240  244  248  252  256  260  264  268  272  276
  280  284  288  292  296  300  304  308  312  316  320  324  328  332
  336  340  344  348  352  356  360  364  368  372  376  380  384  388
  392  396  400  404  408  412  416  420  424  428  432  436  440  444
  448  452  456  460  464  468  472  476  480  484  488  492  496  500
  504  508  512  516  520  524  528  532  536  540  544  548  552  556
  560  564  568  572  576  580  584  588  592  596  600  604  608  612
  616  620  624  628  632  636  640  644  648  652  656  660  664  668
  672  676  680  684  688  692  696  700  704  708  712  716  720  724
  728  732  736  740  744  748  752  756  760  764  768  772  776  780
  784 

In [11]:
box_widths, box_centers_x = np.meshgrid(widths, shifts_x)
print("box_widths\n",box_widths)
print("box_centers_x\n", box_centers_x)
box_heights, box_centers_y = np.meshgrid(heights, shifts_y)
print("box_heights\n",box_heights)
print("len:",len(box_heights))
print("box_centers_y\n",box_centers_y)
print("len:",len(box_centers_y))

box_widths
 [[22.627417 32.       45.254834]
 [22.627417 32.       45.254834]
 [22.627417 32.       45.254834]
 ...
 [22.627417 32.       45.254834]
 [22.627417 32.       45.254834]
 [22.627417 32.       45.254834]]
box_centers_x
 [[   0    0    0]
 [   4    4    4]
 [   8    8    8]
 ...
 [1012 1012 1012]
 [1016 1016 1016]
 [1020 1020 1020]]
box_heights
 [[45.254834 32.       22.627417]
 [45.254834 32.       22.627417]
 [45.254834 32.       22.627417]
 ...
 [45.254834 32.       22.627417]
 [45.254834 32.       22.627417]
 [45.254834 32.       22.627417]]
len: 65536
box_centers_y
 [[   0    0    0]
 [   0    0    0]
 [   0    0    0]
 ...
 [1020 1020 1020]
 [1020 1020 1020]
 [1020 1020 1020]]
len: 65536


In [12]:
box_centers = np.stack([box_centers_y, box_centers_x], axis=2).reshape([-1, 2])
print(box_centers)
print(len(box_centers))

[[   0    0]
 [   0    0]
 [   0    0]
 ...
 [1020 1020]
 [1020 1020]
 [1020 1020]]
196608


In [13]:
box_centers = np.stack([box_centers_y, box_centers_x], axis=2).reshape([-1, 2])
print(box_centers)
print(len(box_centers))

[[   0    0]
 [   0    0]
 [   0    0]
 ...
 [1020 1020]
 [1020 1020]
 [1020 1020]]
196608
